-- 2015-05-30
ALTER TABLE  `CONTATO` CHANGE  `DT_NASCIMENTO`  `DT_NASCIMENTO` DATE NOT NULL;
ALTER TABLE  `SYSFUNCAO` ADD  `ESPECIFICO` INT NULL DEFAULT NULL ;
ALTER TABLE  `PRESSAO_ARTERIAL_MENSAL` DROP FOREIGN KEY  `PRESSAO_ARTERIAL_MENSAL_ibfk_1` ;

ALTER TABLE  `PRESSAO_ARTERIAL_MENSAL` ADD CONSTRAINT  `PRESSAO_ARTERIAL_MENSAL_ibfk_1` FOREIGN KEY (  `ID_CLIENTE` ) REFERENCES  `db_lavivencia`.`CLIENTE` (
`ID`
) ON DELETE CASCADE ON UPDATE RESTRICT ;

ALTER TABLE  `MEDICAO` DROP FOREIGN KEY  `MEDICAO_ibfk_1` ;

ALTER TABLE  `MEDICAO` ADD CONSTRAINT  `MEDICAO_ibfk_1` FOREIGN KEY (  `ID_PRESSAO` ) REFERENCES `db_lavivencia`.`PRESSAO_ARTERIAL_MENSAL` (
`ID`
) ON DELETE CASCADE ON UPDATE RESTRICT ;

-- 2015-05-30
CREATE OR REPLACE 
ALGORITHM = UNDEFINED
VIEW  `v_usuario` AS 
SELECT U.ID, U.LOGIN, F.NOME, F.EMAIL, S.NOME AS PERFIL
FROM  `SYSUSUARIO` U
JOIN FUNCIONARIO F ON F.ID = U.`ID_FUNCIONARIO` 
JOIN SYSPERFIL S ON S.ID = U.FK_SYSPERFIL

-- novo
INSERT INTO `SYSMODULO` (`ID`, `NOME`, `SLUG`, `CHILD`, `MENU_PRINCIPAL`, `OUTROS`) VALUES
(1, 'Configuração Geral', 'up', 0, 0, 0),
(2, 'Funcionário', 'funcionario', 1, 1, 0),
(3, 'Medicamento', 'medicamento', 1, 0, 0),
(4, 'Cliente', 'cliente', 1, 0, 0),
(7, 'Sistema', 'sistema', 1, 0, 0),
(8, 'Usuário', 'usuario', 7, 0, 0),
(9, 'Perfil', 'perfil', 7, 0, 0);